Repository rockphin/gyeonhae-android, pull requests merged in 2021-08, with the labels that each got.

#36 feat(domain): add recognition repository interface
  app/build.gradle
  app/src/main/java/us/gijuno/gyeonhae/domain/repositories/IRecognitionRepository.kt
Labels: Priority: Important, Type: New feature, Scope: Domain

#39 fix(presentation): fix binding property crash
  app/src/main/java/us/gijuno/gyeonhae/presentation/base/BaseActivity.kt
  app/src/main/java/us/gijuno/gyeonhae/presentation/base/BaseFragment.kt
Labels: Type: Bug, Priority: Important, Scope: Presentation

#40 chore: setup color code
  app/src/main/res/values/colors.xml
Labels: Priority: Low, Scope: Presentation, Type: Chore

#41 chore: exclude textview padding
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: Priority: Moderate, Scope: Presentation, Type: Chore

#43 feat(presentation): add inner title layout
  app/src/main/res/layout/layout_inner_title.xml
Labels: Priority: Moderate, Type: New feature, Scope: Presentation

#44 feat(presentation): add menu button layout
  app/src/main/res/layout/layout_menu_button.xml
Labels: Priority: Moderate, Type: New feature, Scope: Presentation

#51 Build main activtity
  app/build.gradle
  app/src/main/java/us/gijuno/gyeonhae/presentation/LayoutMenuButton.kt
  app/src/main/java/us/gijuno/gyeonhae/presentation/MainActivity.kt
  app/src/main/res/drawable/ic_convenience.xml
  app/src/main/res/drawable/ic_guide.xml
  app/src/main/res/drawable/ic_scan.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/round_button.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/layout_menu_button.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: Priority: Important, Type: New feature, Resolution: Implemented, Scope: Presentation
